### ISSUE TITLE
Can't get background image to work.

### ISSUE THREAD

**Issue by thijs666** [reflexjs/reflex#92]
I'm transferring an old website concept which was never finished to the reflex starter template. The only thing I'm stuck with is the background image on the first hero.

I need a background image like this:

![c36f26c1a080ff7a712d942ffea7aa9b](https://user-images.githubusercontent.com/65619302/95086954-641efe00-0721-11eb-8ee2-8c82744a6c9e.png)

As background in the starter template, behind the hero.

![8d6da8f1-b958-4d73-bc2b-8b94cc5709e8](https://user-images.githubusercontent.com/65619302/95087073-84e75380-0721-11eb-9be5-3214eb7ebc23.jpg)

What is the best way to approach this? I hope that someone can get me in the right direction. Thanks in advance.

**Comment by arshad** [comment]
@thijs666 are you using a PNG for the background image or SVG?

**Comment by thijs666** [comment]
@arshad I tried both, but originaly I was using svg.

**Comment by arshad** [comment]
@thijs666 I created an example here: https://codesandbox.io/s/relaxed-meninsky-2cgd3

Since this adds a darker background, we'll also need to update the text and links colors in a few other places. Here are a few files I updated:

`content/pages/index.mdx`: Added the SVG here.
`content/blocks/hero.mdx`: Updated the color of the heading and text.
`content/blocks/header.mdx`: Updated the color of links, branding and the mode toggle.

**Comment by thijs666** [comment]
@arshad Okay thanks, was stuck on this all day long.

So if I'm correct; you change the background of the hero and make a div with the waves underneath it? For this project it works great, but what if I really wanted one big image behind it, would that be possible too or is that way more complicated?

**Comment by arshad** [comment]
@thijs666 Yeah you can do this with `background` props. (Place image in the static directory)

```jsx
<Block src="hero" color="white" background="url(scott-webb-fp4y6MkKyc4-unsplash.jpg) no-repeat bottom" backgroundSize="cover" />
```

See https://2cgd3.sse.codesandbox.io/home-2
